from flask import Flask, jsonify, render_template
import random

app = Flask(__name__)

def generate_random_compliment():
    adjectives = ["amazing"
        ,"awesome"
        ,"outstanding"
        ,"fantastic"
        ,"incredible"
        ,"exceptional"
        ,"remarkable"
        ,"wonderful"
        ,"phenomenal"
        ,"extraordinary"
        ,"terrific"
        ,"impressive"
        ,"marvelous"
        ,"magnificent"
        ,"outstanding"
        ,"excellence"
        ,"superb"
        ,"splendid"
        ,"admirable"
        ,"spectacular"
        ,"fabulous"
        ,"brilliant"
        ,"genius"
        ,"stellar"
        ,"first-rate"
        ,"dazzling"
        ,"breathtaking"
        ,"awe-inspiring"
        ,"exemplary"
        ,"peerless"
        ,"unparalleled"
        ,"top-notch"
        ,"grand"
        ,"majestic"
        ,"supreme"
        ,"noble"
        ,"distinguished"
        ,"virtuoso"
        ,"masterful"
        ,"unrivaled"
        ,"sensational"
        ,"world-class"
        ,"unbeatable"
        ,"exceptionally talented"
        ,"striking"
        ,"classy"
        ,"resplendent"
        ,"splendiferous"
        ,"eminent"
        ,"radiant"
    ]
    nouns = ["achievements"
        ,"accomplishments"
        ,"excellence"
        ,"success"
        ,"triumph"
        ,"victory"
        ,"mastery"
        ,"brilliance"
        ,"talent"
        ,"expertise"
        ,"skill"
        ,"creativity"
        ,"innovation"
        ,"leadership"
        ,"influence"
        ,"charisma"
        ,"kindness"
        ,"generosity"
        ,"compassion"
        ,"wisdom"
        ,"intelligence"
        ,"insight"
        ,"empathy"
        ,"patience"
        ,"dedication"
        ,"commitment"
        ,"diligence"
        ,"resilience"
        ,"positivity"
        ,"optimism"
        ,"endurance"
        ,"fortitude"
        ,"integrity"
        ,"honesty"
        ,"sincerity"
        ,"trustworthiness"
        ,"loyalty"
        ,"support"
        ,"encouragement"
        ,"inspiration"
        ,"motivation"
        ,"enthusiasm"
        ,"spirit"
        ,"courage"
        ,"determination"
        ,"perseverance"
        ,"tenacity"
        ,"happiness"
        ,"joy"
    ]

    noun = random.choice(nouns)
    noun2 = random.choice(nouns)
    adjective = random.choice(adjectives)

    sentence_options = [f"Your {noun} is a shining example of {adjective} {noun}."
        ,f"Your {noun} embodies {adjective} {noun2} at its finest."
        ,f"Your {noun} reflects your {adjective} {noun2} brilliantly."
        ,f"You've achieved {adjective} {noun} through your hard work."
        ,f"Your {noun} demonstrates your {adjective} {noun2} remarkably."
        ,f"Your {noun} showcases your {adjective} {noun2} beautifully."
        ,f"Your {noun} is a testament to your {adjective} {noun2}."
        ,f"Your {noun} displays your {adjective} {noun2} with pride."
        ,f"You possess an {adjective} {noun2} that inspires others."
        ,f"Your {noun} is evidence of your {adjective} {noun2} nature."
        ,f"You bring {adjective} {noun} to everything you do."
        ,f"Your {noun} reflects your {adjective} {noun2} qualities."
        ,f"Your {noun} is a source of {adjective} {noun2}."
        ,f"Your {noun} is a true example of {adjective} {noun2}."
        ,f"You've achieved {adjective} {noun2} through dedication."
        ,f"Your {noun} radiates {adjective} {noun2} to those around you."
        ,f"You inspire with your {adjective} {noun} {noun2}."
        ,f"Your {noun} is filled with {adjective} {noun2}."
        ,f"Your {noun} is a symbol of {adjective} {noun2}."
        ,f"Your {noun} is a reminder of your {adjective} {noun2}."
    ]

    compliment = random.choice(sentence_options)
    return compliment

@app.route('/')
def get_compliment():
    compliment = generate_random_compliment()
    return jsonify({'compliment': compliment})

if __name__ == '__main__':
    app.run(debug=True)